Resources:
  SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
          Endpoint: ${self:provider.environment.TOPIC_SUBSCRIPTION_ENDPOINT_EMAIL}
          Protocol: email
          TopicArn:
            Fn::Join:
              - ''
              - - 'arn:aws:sns:'
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":"
                - Fn::GetAtt:
                  - SNSTopic
                  - TopicName


# Print out the name of the bucket that is created
Outputs:
  SNSSubscription:
    Value:
      Ref: SNSSubscription
